apiVersion: habitat.sh/v1beta1
kind: Habitat
metadata:
  name: example-leader-follower-habitat
  labels:
    source: operator-example
    app: leader-follower-habitat
customVersion: v1beta2
spec:
  v1beta2:
    # the core/redis habitat service packaged as a Docker image
    image: habitat/redis-hab
    # While it is possible to deploy only one pod with a service
    # instance in the leader-follower topology, at least 3 instances
    # are required for services to be started by the supervisor.
    count: 1
    service:
      name: redis
      topology: leader
      # if not present, defaults to "default"
      group: foobar
